name: train_restoration
use_tb_logger: true
model_type: RefRestorationModel
map_type: online_CUFED_swap
scale: 1
crop_border: ~
set_CUDA_VISIBLE_DEVICES: ~
gpu_ids: [0, 1]

# datasets
datasets:
  train:
    name: Heart_mat
    type: RefCUFEDDataset
    ksp_dir: /gpfs/scrubbed/hanruish/cine_recon/datasets/cmr2025/training/FullySampled    # path to k-space .npy files  [T, C, H, W] complex
    mask_dir: /gpfs/scrubbed/hanruish/cine_recon/datasets/cmr2025/training/Mask_Radial8   # path to mask .npy files      [T, H, W]
    sense_dir: /gpfs/scrubbed/hanruish/cine_recon/datasets/cmr2025/training/SenseMaps   # path to sensitivity .npy files [T, C, H, W] complex
    split_ratio: 0.8  # train/val split ratio (80% train, 20% val)

    gt_size: 256
    use_flip: true
    use_rot: true

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 4
    dataset_enlarge_ratio: 1000

  val:
    name: val_Heart5_mat
    type: RefDataset
    # data dirs and split_ratio are inherited from train

# network structures
network_g:
  type: SwinUnetv3RestorationNet
  ngf: 16
  n_blocks: 4
  groups: 4
  embed_dim: 16
  depths: [4,4]
  num_heads: [4,4]
  window_size: 8
  use_checkpoint: True
network_d:
  type: ImageDiscriminator
  in_nc: 2
  ndf: 32
network_map:
  type: FlowSimCorrespondenceGenerationArch
  patch_size: 3
  stride: 1
  vgg_layer_list: ['relu1_1', 'relu2_1', 'relu3_1']
  vgg_type: 'vgg19'
network_extractor:
  type: ContrasExtractorSep

# path
path:
  pretrain_model_g: ~
  pretrain_model_d: ~
  pretrain_model_feature_extractor: ./experiments/pretrained_model/feature_extraction.pth
  strict_load: false  # true
  resume_state: ~   
  root: experiments/train/

# training settings: learning rate scheme, loss
train:
  lr_g: !!float 1e-3
  lr_offset: !!float 1e-3
  lr_relu2_offset: !!float 1e-5
  lr_relu3_offset: !!float 1e-6
  weight_decay_g: 0
  beta_g: [0.9, 0.999]
  lr_d: !!float 1e-4
  weight_decay_d: 0
  beta_d: [0.9, 0.999]
  lr_scheme: MultiStepLR

  niter: 500000 #
  warmup_iter: -1  # no warm up
  net_g_pretrain_steps: 0
  lr_steps: [400000, 500000] #[27000, 63000]
  lr_gamma: 0.1

  pixel_criterion: L1Loss
  pixel_weight: !!float 1.0
  perceptual_opt:
    layer_weights:
      'relu5_1': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1e-4
    style_weight: 0
    norm_img: false
    criterion: fro
  gan_type: wgan
  gan_weight: !!float 1e-6
  grad_penalty_weight: !!float 10.0

  net_d_steps: 1
  net_d_init_steps: 0

  manual_seed: 10

val:
  val_freq: !!float 2.43e3
  save_img: False #True

# logger
logger:
  print_freq: 243
  save_checkpoint_freq: !!float 2.43e3

dist_params:
  backend: nccl
  port: 29746
